version: "2"
services:

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    links:
      - mongodb
    networks:
      - backend
  mongodb:
    image: mongo
    volumes:
      - /storage/docker/mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend


networks:
  backend:
    driver: bridge